//
//  Constants.swift
//  TheBest-iOS
//
//  Created by Sherif Darwish on 8/2/20.
//  Copyright © 2020 Sherif Darwish. All rights reserved.
//

import Foundation

let MAX_YEARS = Calendar.current.component(.year, from: Date()) - 18

let MONTHS_EN = [
    "Jan" : "01",
    "Feb" : "02",
    "Mar" : "03",
    "Apr" : "04",
    "May" : "05",
    "Jun" : "06",
    "Jul" : "07",
    "Aug" : "08",
    "Sep" : "09",
    "Oct" : "10",
    "Nov" : "11",
    "Dec" : "12"
]

let COUNTRIES_EN = [
    "Spain" : "ES",
    "Australia" : "AU",
    "Afghanistan" : "AF",
    "Palestinian Territories" : "PS",
    "Argentina" : "AR",
    "Jordan" : "JO",
    "United Arab Emirates" : "AE",
    "Bahrain" : "BH",
    "Brazil" : "BR",
    "Portugal" : "PT",
    "Algeria" : "DZ",
    "Denmark" : "DK",
    "Senegal" : "SN",
    "Sudan" : "SD",
    "Sweden" : "SE",
    "Somalia" : "SO",
    "China" : "CN",
    "Iraq" : "IQ",
    "Philippines" : "PH",
    "Cameron" : "CM",
    "Kuwait" : "KW",
    "Germany" : "DE",
    "Morroco" : "MA",
    "Mexico" : "MX",
    "Saudi Arabia" : "SA",
    "United Kingdom" : "GB",
    "Norway" : "NO",
    "Austria" : "AT",
    "Hungary" : "NE",
    "India" : "IN",
    "United States" : "US",
    "Japan" : "JP",
    "Yemen" : "YE",
    "Greec" : "GR",
    "Indonesia" : "ID",
    "Uruguay" : "UY",
    "Ukrania" : "UA",
    "Iran" : "IR",
    "Ireland" : "IE",
    "Iceland" : "IS",
    "Italy" : "IT",
    "Paraguay" : "PY",
    "Pakistan" : "PK",
    "Belgium" : "BE",
    "Bulgaria" : "BG",
    "Poland" : "PL",
    "Bolivia" : "BO",
    "Peru" : "PE",
    "Tailand" : "TH",
    "Taiwan" : "TW",
    "Turkey" : "TR",
    "Chile" : "CL",
    "Tunisia" : "TN",
    "Gibraltar" : "GI",
    "Comoros" : "KM",
    "South Africa" : "ZA",
    "South Sudan" : "SS",
    "Russia" : "RU",
    "Romania" : "RO",
    "Singapore" : "SG",
    "Syria" : "SY",
    "Switzerland" : "CH",
    "Oman" : "OM",
    "Ghana" : "GH",
    "France" : "FR",
    "Venezuela" : "VE",
    "Finland" : "FI",
    "Cyprus" : "CY",
    "Croatia" : "HR",
    "Canada" : "CA",
    "Cuba" : "CU",
    "South Korea" : "KR",
    "North Korea" : "KP",
    "Lebanon" : "LB",
    "Libya" : "LY",
    "Malta" : "MT",
    "Mali" : "ML",
    "Malaysia" : "MY",
    "Madagascar" : "MG",
    "Egypt" : "EG",
    "Mauritania" : "MR",
    "Nigiria" : "NG",
    "New Zealand" : "NZ",
    "Netherlands" : "NL"
]
